spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mossol_oc?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: amos_doan
    password: test!123
    initialization-mode: always
    driver-class-name: com.mysql.jdbc.Driver # For Windows Environment
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    serialization.WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC
logging.level:
  org:
  hibernate.SQL: DEBUG

mossol:
  jwtSecret: "test"
  jwtExpireTimeMillis: 300000
