spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mossol_oc?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: test
    password: test
    initialization-mode: always
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

logging.level:
  org:
  hibernate.SQL: DEBUG

mossol:
  auth:
    jwtSecret: "test"
    jwtExpireTimeMillis: 3000
